[theme]
base="light"
primaryColor="#4A90E2"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"
font="sans serif"

[darkTheme]
base="dark"
primaryColor="#1E88E5"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
